# Generated by Django 3.2.8 on 2023-02-08 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_user_user_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.CharField(max_length=255, verbose_name='메뉴 아이디')),
                ('menu_name', models.CharField(max_length=255, verbose_name='메뉴명')),
                ('menu_parent', models.CharField(max_length=255, verbose_name='상위메뉴 PK')),
                ('menu_link', models.CharField(max_length=255, verbose_name='메뉴 링크')),
                ('menu_order', models.FloatField(null=True, verbose_name='메뉴 정렬 순서')),
                ('user_group', models.ForeignKey(db_column='user_group', on_delete=django.db.models.deletion.CASCADE, to='account.user', verbose_name='사용자 그룹')),
            ],
        ),
    ]
